name: dev-6674
summary: Dev 6674 Dev

description: |
      Starts the 6674 App

version: git
grade: stable
confinement: devmode
base: core20

architectures:
  - build-on: [arm64, armhf, amd64]

apps:
  dev-6674:
    command: bin/dev-6674
    plugs: [home]

parts:
  dev-6674:
    plugin: python
    source: https://github.com/BlueNexus6674/Dev_6674.git
    source-type: git
    python-packages:
      - pyqt5 == 5.15.2
    stage-packages:
      - python3-pyqt5
