# Form implementation generated from reading ui file 'input.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button1 = QtWidgets.QPushButton(self.centralwidget)
        self.button1.setGeometry(QtCore.QRect(80, 250, 89, 25))
        self.button1.setObjectName("button1")
        self.ROSLabel = QtWidgets.QLabel(self.centralwidget)
        self.ROSLabel.setGeometry(QtCore.QRect(0, 0, 45, 45))
        self.ROSLabel.setText("")
        self.ROSLabel.setPixmap(QtGui.QPixmap("../src/Data/LEDOff.png"))
        self.ROSLabel.setScaledContents(True)
        self.ROSLabel.setObjectName("ROSLabel")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(250, 150, 43, 23))
        self.spinBox.setObjectName("spinBox")
        self.PB = QtWidgets.QProgressBar(self.centralwidget)
        self.PB.setGeometry(QtCore.QRect(190, 250, 118, 23))
        self.PB.setProperty("value", 0)
        self.PB.setObjectName("PB")
        self.button1.raise_()
        self.spinBox.raise_()
        self.PB.raise_()
        self.ROSLabel.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 19))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport_ROS_Py = QtGui.QAction(MainWindow)
        self.actionImport_ROS_Py.setObjectName("actionImport_ROS_Py")
        self.menuFile.addAction(self.actionImport_ROS_Py)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.button1.clicked.connect(self.spinBox.stepUp)
        self.button1.clicked.connect(MainWindow.yesclick)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button1.setText(_translate("MainWindow", "PressMe"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionImport_ROS_Py.setText(_translate("MainWindow", "Import ROS Py"))
