# Form implementation generated from reading ui file 'QT1.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import UI_Lib.UI_Main

class MainWindow(QtWidgets.QMainWindow, UI_Lib.UI_Main.Ui_MainWindow): #Inhereit the QtWidets.QMainWindow class (i.e. default main window)
	def __init__(self):
		super().__init__()
		self.setupUi(self)
		
	def SetupUI(self, MainWindow):
		super().setupUi(MainWindow)
		
	def yesclick(self):
		print("s")
		self.label1.setText("Pushed")
   

